/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.23
 * Generated at: 2024-05-21 14:15:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class newFilm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("/views/common/taglib.jsp", Long.valueOf(1690799496778L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1602874032000L));
    _jspx_dependants.put("/views/admin/common/head.jsp", Long.valueOf(1690903392673L));
    _jspx_dependants.put("/views/admin/common/footer.jsp", Long.valueOf(1690902337797L));
    _jspx_dependants.put("/views/admin/common/header.jsp", Long.valueOf(1691150084205L));
    _jspx_dependants.put("/views/admin/common/assied.jsp", Long.valueOf(1715881775266L));
    _jspx_dependants.put("jar:file:/D:/BackEnd/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BackEnd/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602848772000L));
    _jspx_dependants.put("jar:file:/D:/BackEnd/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BackEnd/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/fn.tld", Long.valueOf(1602848772000L));
    _jspx_dependants.put("jar:file:/D:/BackEnd/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BackEnd/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/fmt.tld", Long.valueOf(1602848772000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>FilmViet - Thêm Video</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"icon\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"sweetalert2.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"/>\r\n");
      out.write("<style>\r\n");
      out.write("    body::-webkit-scrollbar {\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* bï¿½n tay animation */\r\n");
      out.write("    .wave {\r\n");
      out.write("        animation-name: wave-animation;\r\n");
      out.write("        animation-duration: 2.5s;\r\n");
      out.write("        animation-iteration-count: infinite;\r\n");
      out.write("        transform-origin: 70% 70%;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes wave-animation {\r\n");
      out.write("        0% {\r\n");
      out.write("            transform: rotate(0.0deg)\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        10% {\r\n");
      out.write("            transform: rotate(14.0deg)\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        20% {\r\n");
      out.write("            transform: rotate(-8.0deg)\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        30% {\r\n");
      out.write("            transform: rotate(14.0deg)\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        40% {\r\n");
      out.write("            transform: rotate(-4.0deg)\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        50% {\r\n");
      out.write("            transform: rotate(10.0deg)\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        60% {\r\n");
      out.write("            transform: rotate(0.0deg)\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        100% {\r\n");
      out.write("            transform: rotate(0.0deg)\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!--  Body Wrapper -->\r\n");
      out.write("	<div class=\"page-wrapper\" id=\"main-wrapper\" data-layout=\"vertical\"\r\n");
      out.write("		data-navbarbg=\"skin6\" data-sidebartype=\"full\"\r\n");
      out.write("		data-sidebar-position=\"fixed\" data-header-position=\"fixed\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Sidebar Start -->\r\n");
      out.write("		");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<aside class=\"left-sidebar\">\r\n");
      out.write("	<!-- Sidebar scroll-->\r\n");
      out.write("	<div>\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"brand-logo d-flex align-items-center justify-content-between\">\r\n");
      out.write("			<a href=\"dashboarh\" class=\"text-nowrap logo-img\"> <img\r\n");
      out.write("				src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("				width=\"180\" class=\"ps-4\" />\r\n");
      out.write("			</a>\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"close-btn d-xl-none d-block sidebartoggler cursor-pointer\"\r\n");
      out.write("				id=\"sidebarCollapse\">\r\n");
      out.write("				<i class=\"ti ti-x fs-8\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Sidebar navigation-->\r\n");
      out.write("		<nav class=\"sidebar-nav scroll-sidebar\" data-simplebar=\"\">\r\n");
      out.write("			<ul id=\"sidebarnav\">\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-small-cap\"><i\r\n");
      out.write("					class=\"ti ti-dots nav-small-cap-icon fs-4\"></i> <span\r\n");
      out.write("					class=\"hide-menu\">Trang Chủ</span></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("					href=\"dashboarh\" aria-expanded=\"false\"> <span> <i\r\n");
      out.write("							class=\"ti ti-layout-dashboard\"></i>\r\n");
      out.write("					</span> <span class=\"hide-menu\">DashBoarh</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-small-cap\"><i\r\n");
      out.write("					class=\"ti ti-dots nav-small-cap-icon fs-4\"></i> <span\r\n");
      out.write("					class=\"hide-menu\">QUẢN LÝ VIDEO</span></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("					href=\"videoviews\" aria-expanded=\"false\"> <span> <i\r\n");
      out.write("							class=\"ti ti-cards\"></i>\r\n");
      out.write("					</span> <span class=\"hide-menu\">Tạo Phim</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("					href=\"videodisabled\" aria-expanded=\"false\"> <span> <i\r\n");
      out.write("							class=\"ti ti-list-details\"></i>\r\n");
      out.write("					</span> <span class=\"hide-menu\">Phim ngừng công chiếu</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li class=\"nav-small-cap\"><i\r\n");
      out.write("						class=\"ti ti-dots nav-small-cap-icon fs-4\"></i> <span\r\n");
      out.write("						class=\"hide-menu\">QUẢN LÝ THÔNG BÁO</span></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("											href=\"notifications\" aria-expanded=\"false\"> <span> <i\r\n");
      out.write("						class=\"ti ti-apps\"></i>\r\n");
      out.write("					</span> <span class=\"hide-menu\">Danh sách thông báo</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-small-cap\"><i\r\n");
      out.write("					class=\"ti ti-dots nav-small-cap-icon fs-4\"></i> <span\r\n");
      out.write("					class=\"hide-menu\">QUẢN LÝ NGƯỜI DÙNG</span></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("					href=\"datauser\" aria-expanded=\"false\"> <span> <i\r\n");
      out.write("							class=\"ti ti-apps\"></i>\r\n");
      out.write("					</span> <span class=\"hide-menu\">Danh sách người dùng</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-small-cap\"><i\r\n");
      out.write("					class=\"ti ti-dots nav-small-cap-icon fs-4\"></i> <span\r\n");
      out.write("					class=\"hide-menu\">BÁO CÁO - THỐNG KÊ</span></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("					href=\"likeonevideo\" aria-expanded=\"false\"> <span> <i\r\n");
      out.write("							class=\"ti ti-mood-happy\"></i>\r\n");
      out.write("					</span> <span class=\"hide-menu\">Lượt thích từng video</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("					href=\"userlike\" aria-expanded=\"false\"> <span> <i\r\n");
      out.write("							class=\"ti ti-thumb-up\"></i>\r\n");
      out.write("					</span> <span class=\"hide-menu\">Người dùng yêu thích</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("					href=\"usershare\" aria-expanded=\"false\"> <span> <i\r\n");
      out.write("							class=\"ti ti-share\"></i>\r\n");
      out.write("					</span> <span class=\"hide-menu\">Lọc người dùng gửi & nhận</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("					href=\"doanhthu\" aria-expanded=\"false\"> <span> <i\r\n");
      out.write("							class=\"ti ti-align-box-right-top\"></i>\r\n");
      out.write("					</span> <span class=\"hide-menu\">Doanh thu</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!-- End Sidebar navigation -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End Sidebar scroll-->\r\n");
      out.write("</aside>");
      out.write("\r\n");
      out.write("		<!--  Sidebar End -->\r\n");
      out.write("\r\n");
      out.write("		<!--  Main wrapper -->\r\n");
      out.write("		<div class=\"body-wrapper\">\r\n");
      out.write("\r\n");
      out.write("			<!--  Header Start -->\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("<header class=\"app-header\">\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("		<ul class=\"navbar-nav\">\r\n");
      out.write("			<li class=\"nav-item d-block d-xl-none\"><a\r\n");
      out.write("				class=\"nav-link sidebartoggler nav-icon-hover\" id=\"headerCollapse\"\r\n");
      out.write("				href=\"javascript:void(0)\"> <i class=\"ti ti-menu-2\"></i>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link nav-icon-hover\"\r\n");
      out.write("				href=\"javascript:void(0)\"> <i class=\"ti ti-bell-ringing\"></i>\r\n");
      out.write("					<div class=\"notification bg-primary rounded-circle\"></div>\r\n");
      out.write("			</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<strong>Xin chào ! ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.currentAdmin.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <span\r\n");
      out.write("			class=\"wave\">👋</span></strong>\r\n");
      out.write("		<div class=\"navbar-collapse justify-content-end px-0\" id=\"navbarNav\">\r\n");
      out.write("			<ul\r\n");
      out.write("				class=\"navbar-nav flex-row ms-auto align-items-center justify-content-end\">\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a\r\n");
      out.write("					class=\"nav-link nav-icon-hover\" id=\"drop2\"\r\n");
      out.write("					data-bs-toggle=\"dropdown\" aria-expanded=\"false\"><img\r\n");
      out.write("						src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("						width=\"35\" height=\"35\" class=\"rounded-circle\"> </a>\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"dropdown-menu dropdown-menu-end dropdown-menu-animate-up\"\r\n");
      out.write("						aria-labelledby=\"drop2\">\r\n");
      out.write("						<div class=\"message-body\">\r\n");
      out.write("							<a style=\"cursor: pointer;\"\r\n");
      out.write("								class=\"d-flex align-items-center gap-2 dropdown-item\"> <i\r\n");
      out.write("								class=\"ti ti-user fs-6\"></i>\r\n");
      out.write("								<p class=\"mb-0 fs-3\">Thông tin cá nhân</p>\r\n");
      out.write("							</a> <a style=\"cursor: pointer;\"\r\n");
      out.write("								class=\"d-flex align-items-center gap-2 dropdown-item\"> <i\r\n");
      out.write("								class=\"ti ti-replace fs-6\"></i>\r\n");
      out.write("								<p class=\"mb-0 fs-3\">Đổi mật khẩu</p>\r\n");
      out.write("							</a> <a href=\"logoutadmin\"\r\n");
      out.write("								class=\"btn btn-outline-primary mx-3 mt-2 d-block\">Đăng xuất</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("			<!--  Header End -->\r\n");
      out.write("\r\n");
      out.write("			<div class=\"container-fluid\">\r\n");
      out.write("				<div class=\"card\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<h5 class=\"card-title fw-semibold mb-4 mt-2\">Thêm Mới Phim</h5>\r\n");
      out.write("						<div class=\"card\">\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<form onsubmit=\"return validateNewFilm()\" action=\"videoadd\"\r\n");
      out.write("									method=\"post\">\r\n");
      out.write("\r\n");
      out.write("									<div class=\"mb-3\">\r\n");
      out.write("										<label for=\"title\" class=\"form-label\">Tên phim</label> <input\r\n");
      out.write("											type=\"text\" class=\"form-control\" name=\"title\" id=\"title\"\r\n");
      out.write("											placeholder=\"Tên phim...\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"mb-3\">\r\n");
      out.write("										<label for=\"link-phim\" class=\"form-label\">Link phim</label> <input\r\n");
      out.write("											type=\"text\" class=\"form-control\" name=\"href\" id=\"link-phim\"\r\n");
      out.write("											placeholder=\"Href...\" onblur=\"fillHrefOnPoster()\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"mb-3\">\r\n");
      out.write("										<label for=\"dao-dien\" class=\"form-label\">Đạo diễn</label> <input\r\n");
      out.write("											type=\"text\" class=\"form-control\" name=\"daodien\" id=\"dao-dien\"\r\n");
      out.write("											placeholder=\"Dạo diễn...\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"mb-3\">\r\n");
      out.write("										<label for=\"dien-vien\" class=\"form-label\">Diễn viên</label> <input\r\n");
      out.write("											type=\"text\" class=\"form-control\" name=\"dienvien\"\r\n");
      out.write("											id=\"dien-vien\" placeholder=\"Diễn viên...\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"mb-3\">\r\n");
      out.write("										<label for=\"the-loai\" class=\"form-label\">Thể loại</label> <input\r\n");
      out.write("											type=\"text\" class=\"form-control\" name=\"category\"\r\n");
      out.write("											id=\"the-loai\" placeholder=\"Thể loại...\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"mb-3\">\r\n");
      out.write("										<label for=\"mo-ta\" class=\"form-label\">Mô tả</label> <input\r\n");
      out.write("											type=\"text\" class=\"form-control\" name=\"mota\" id=\"mo-ta\"\r\n");
      out.write("											placeholder=\"Mô tả...\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"mb-3\">\r\n");
      out.write("										<label class=\"form-label\">Giá</label> <input type=\"text\"\r\n");
      out.write("											class=\"form-control\" oninput=\"formatPrice(this)\" name=\"price\"\r\n");
      out.write("											placeholder=\"Giá...\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"mb-3\">\r\n");
      out.write("										<label for=\"noted\" class=\"form-label\">Nội dung</label>\r\n");
      out.write("										<textarea class=\"form-control\" id=\"noted\" name=\"noted\"\r\n");
      out.write("											rows=\"5\" placeholder=\"Nội dung...\"></textarea>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<input type=\"hidden\" class=\"form-control\" id=\"poster\"\r\n");
      out.write("										name=\"poster\">\r\n");
      out.write("\r\n");
      out.write("									<button type=\"submit\" class=\"btn btn-success\">Xác nhận</button>\r\n");
      out.write("									<button type=\"reset\" class=\"btn btn-primary\">Làm mới</button>\r\n");
      out.write("									<a class=\"btn btn-danger float-end\" href=\"videoviews\"\r\n");
      out.write("										role=\"button\">Trở về</a>\r\n");
      out.write("\r\n");
      out.write("								</form>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"sweetalert2.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f10(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f11(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("\r\n");

Boolean loginAdmin = (Boolean) session.getAttribute("loginAdmin");
Boolean loginAdminFail = (Boolean) session.getAttribute("loginAdminFail");

if (loginAdmin != null) {
	if (loginAdmin) {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	showSwalAlert('success', 'Đăng nhập thành công !');\r\n");
      out.write("</script>\r\n");

} else {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	showSwalAlert('error', 'Sai thông tin đăng nhập !');\r\n");
      out.write("</script>\r\n");

}
session.removeAttribute("loginAdmin");
}

if (loginAdminFail != null) {
if (loginAdminFail) {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	showSwalAlert('warning', 'Tài khoản không hoạt động !');\r\n");
      out.write("</script>\r\n");

}
session.removeAttribute("loginAdminFail");
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function fillHrefOnPoster() {\r\n");
      out.write("			var href = document.getElementById(\"link-phim\").value;\r\n");
      out.write("			var poster = document.getElementById(\"poster\");\r\n");
      out.write("			poster.value = \"https://img.youtube.com/vi/\" + href\r\n");
      out.write("					+ \"/maxresdefault.jpg\";\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /views/admin/common/head.jsp(1,24) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/views/admin/assets/images/favicon.png");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /views/admin/common/head.jsp(5,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/views/admin/assets/css/styles.min.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /views/admin/common/assied.jsp(10,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/views/admin/assets/images/logo.png");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /views/admin/common/header.jsp(23,11) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/views/admin/assets/images/user.jpg");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /views/admin/common/footer.jsp(6,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/views/template/user/js/jquery-3.3.1.min.js");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /views/admin/common/footer.jsp(7,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/views/admin/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /views/admin/common/footer.jsp(8,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/views/admin/assets/js/sidebarmenu.js");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /views/admin/common/footer.jsp(9,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/views/admin/assets/js/app.min.js");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /views/admin/common/footer.jsp(10,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/views/admin/assets/libs/apexcharts/dist/apexcharts.min.js");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /views/admin/common/footer.jsp(11,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("/views/admin/assets/libs/simplebar/dist/simplebar.js");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f10(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f10 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f10_reused = false;
    try {
      _jspx_th_c_005furl_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f10.setParent(null);
      // /views/admin/common/footer.jsp(12,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f10.setValue("/views/admin/assets/js/dashboard.js");
      int _jspx_eval_c_005furl_005f10 = _jspx_th_c_005furl_005f10.doStartTag();
      if (_jspx_th_c_005furl_005f10.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f10);
      _jspx_th_c_005furl_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f10, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f11(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f11 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f11_reused = false;
    try {
      _jspx_th_c_005furl_005f11.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f11.setParent(null);
      // /views/admin/common/footer.jsp(13,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f11.setValue("/views/admin/assets/js/validateAdmin.js");
      int _jspx_eval_c_005furl_005f11 = _jspx_th_c_005furl_005f11.doStartTag();
      if (_jspx_th_c_005furl_005f11.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f11);
      _jspx_th_c_005furl_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f11, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f11_reused);
    }
    return false;
  }
}
