/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.23
 * Generated at: 2024-05-21 20:21:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class notifications_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("/views/common/taglib.jsp", Long.valueOf(1690799496778L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1602874032000L));
    _jspx_dependants.put("/views/admin/common/head.jsp", Long.valueOf(1690903392673L));
    _jspx_dependants.put("/views/admin/common/footer.jsp", Long.valueOf(1690902337797L));
    _jspx_dependants.put("/views/admin/common/header.jsp", Long.valueOf(1691150084205L));
    _jspx_dependants.put("/views/admin/common/assied.jsp", Long.valueOf(1715881775266L));
    _jspx_dependants.put("jar:file:/D:/BackEnd/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BackEnd/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602848772000L));
    _jspx_dependants.put("jar:file:/D:/BackEnd/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BackEnd/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/fn.tld", Long.valueOf(1602848772000L));
    _jspx_dependants.put("jar:file:/D:/BackEnd/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BackEnd/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/fmt.tld", Long.valueOf(1602848772000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>FilmViet - Danh sách thông báo</title>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("<link rel=\"icon\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"sweetalert2.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"/>\r\n");
      out.write("<style>\r\n");
      out.write("    body::-webkit-scrollbar {\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* bï¿½n tay animation */\r\n");
      out.write("    .wave {\r\n");
      out.write("        animation-name: wave-animation;\r\n");
      out.write("        animation-duration: 2.5s;\r\n");
      out.write("        animation-iteration-count: infinite;\r\n");
      out.write("        transform-origin: 70% 70%;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes wave-animation {\r\n");
      out.write("        0% {\r\n");
      out.write("            transform: rotate(0.0deg)\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        10% {\r\n");
      out.write("            transform: rotate(14.0deg)\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        20% {\r\n");
      out.write("            transform: rotate(-8.0deg)\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        30% {\r\n");
      out.write("            transform: rotate(14.0deg)\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        40% {\r\n");
      out.write("            transform: rotate(-4.0deg)\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        50% {\r\n");
      out.write("            transform: rotate(10.0deg)\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        60% {\r\n");
      out.write("            transform: rotate(0.0deg)\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        100% {\r\n");
      out.write("            transform: rotate(0.0deg)\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"page-wrapper\" id=\"main-wrapper\" data-layout=\"vertical\"\r\n");
      out.write("     data-navbarbg=\"skin6\" data-sidebartype=\"full\"\r\n");
      out.write("     data-sidebar-position=\"fixed\" data-header-position=\"fixed\">\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<aside class=\"left-sidebar\">\r\n");
      out.write("	<!-- Sidebar scroll-->\r\n");
      out.write("	<div>\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"brand-logo d-flex align-items-center justify-content-between\">\r\n");
      out.write("			<a href=\"dashboarh\" class=\"text-nowrap logo-img\"> <img\r\n");
      out.write("				src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("				width=\"180\" class=\"ps-4\" />\r\n");
      out.write("			</a>\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"close-btn d-xl-none d-block sidebartoggler cursor-pointer\"\r\n");
      out.write("				id=\"sidebarCollapse\">\r\n");
      out.write("				<i class=\"ti ti-x fs-8\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Sidebar navigation-->\r\n");
      out.write("		<nav class=\"sidebar-nav scroll-sidebar\" data-simplebar=\"\">\r\n");
      out.write("			<ul id=\"sidebarnav\">\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-small-cap\"><i\r\n");
      out.write("					class=\"ti ti-dots nav-small-cap-icon fs-4\"></i> <span\r\n");
      out.write("					class=\"hide-menu\">Trang Chủ</span></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("					href=\"dashboarh\" aria-expanded=\"false\"> <span> <i\r\n");
      out.write("							class=\"ti ti-layout-dashboard\"></i>\r\n");
      out.write("					</span> <span class=\"hide-menu\">DashBoarh</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-small-cap\"><i\r\n");
      out.write("					class=\"ti ti-dots nav-small-cap-icon fs-4\"></i> <span\r\n");
      out.write("					class=\"hide-menu\">QUẢN LÝ VIDEO</span></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("					href=\"videoviews\" aria-expanded=\"false\"> <span> <i\r\n");
      out.write("							class=\"ti ti-cards\"></i>\r\n");
      out.write("					</span> <span class=\"hide-menu\">Tạo Phim</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("					href=\"videodisabled\" aria-expanded=\"false\"> <span> <i\r\n");
      out.write("							class=\"ti ti-list-details\"></i>\r\n");
      out.write("					</span> <span class=\"hide-menu\">Phim ngừng công chiếu</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li class=\"nav-small-cap\"><i\r\n");
      out.write("						class=\"ti ti-dots nav-small-cap-icon fs-4\"></i> <span\r\n");
      out.write("						class=\"hide-menu\">QUẢN LÝ THÔNG BÁO</span></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("											href=\"notifications\" aria-expanded=\"false\"> <span> <i\r\n");
      out.write("						class=\"ti ti-apps\"></i>\r\n");
      out.write("					</span> <span class=\"hide-menu\">Danh sách thông báo</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-small-cap\"><i\r\n");
      out.write("					class=\"ti ti-dots nav-small-cap-icon fs-4\"></i> <span\r\n");
      out.write("					class=\"hide-menu\">QUẢN LÝ NGƯỜI DÙNG</span></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("					href=\"datauser\" aria-expanded=\"false\"> <span> <i\r\n");
      out.write("							class=\"ti ti-apps\"></i>\r\n");
      out.write("					</span> <span class=\"hide-menu\">Danh sách người dùng</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-small-cap\"><i\r\n");
      out.write("					class=\"ti ti-dots nav-small-cap-icon fs-4\"></i> <span\r\n");
      out.write("					class=\"hide-menu\">BÁO CÁO - THỐNG KÊ</span></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("					href=\"likeonevideo\" aria-expanded=\"false\"> <span> <i\r\n");
      out.write("							class=\"ti ti-mood-happy\"></i>\r\n");
      out.write("					</span> <span class=\"hide-menu\">Lượt thích từng video</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("					href=\"userlike\" aria-expanded=\"false\"> <span> <i\r\n");
      out.write("							class=\"ti ti-thumb-up\"></i>\r\n");
      out.write("					</span> <span class=\"hide-menu\">Người dùng yêu thích</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("					href=\"usershare\" aria-expanded=\"false\"> <span> <i\r\n");
      out.write("							class=\"ti ti-share\"></i>\r\n");
      out.write("					</span> <span class=\"hide-menu\">Lọc người dùng gửi & nhận</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"sidebar-item\"><a class=\"sidebar-link\"\r\n");
      out.write("					href=\"doanhthu\" aria-expanded=\"false\"> <span> <i\r\n");
      out.write("							class=\"ti ti-align-box-right-top\"></i>\r\n");
      out.write("					</span> <span class=\"hide-menu\">Doanh thu</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!-- End Sidebar navigation -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End Sidebar scroll-->\r\n");
      out.write("</aside>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"body-wrapper\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<header class=\"app-header\">\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("		<ul class=\"navbar-nav\">\r\n");
      out.write("			<li class=\"nav-item d-block d-xl-none\"><a\r\n");
      out.write("				class=\"nav-link sidebartoggler nav-icon-hover\" id=\"headerCollapse\"\r\n");
      out.write("				href=\"javascript:void(0)\"> <i class=\"ti ti-menu-2\"></i>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link nav-icon-hover\"\r\n");
      out.write("				href=\"javascript:void(0)\"> <i class=\"ti ti-bell-ringing\"></i>\r\n");
      out.write("					<div class=\"notification bg-primary rounded-circle\"></div>\r\n");
      out.write("			</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<strong>Xin chào ! ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.currentAdmin.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <span\r\n");
      out.write("			class=\"wave\">👋</span></strong>\r\n");
      out.write("		<div class=\"navbar-collapse justify-content-end px-0\" id=\"navbarNav\">\r\n");
      out.write("			<ul\r\n");
      out.write("				class=\"navbar-nav flex-row ms-auto align-items-center justify-content-end\">\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a\r\n");
      out.write("					class=\"nav-link nav-icon-hover\" id=\"drop2\"\r\n");
      out.write("					data-bs-toggle=\"dropdown\" aria-expanded=\"false\"><img\r\n");
      out.write("						src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("						width=\"35\" height=\"35\" class=\"rounded-circle\"> </a>\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"dropdown-menu dropdown-menu-end dropdown-menu-animate-up\"\r\n");
      out.write("						aria-labelledby=\"drop2\">\r\n");
      out.write("						<div class=\"message-body\">\r\n");
      out.write("							<a style=\"cursor: pointer;\"\r\n");
      out.write("								class=\"d-flex align-items-center gap-2 dropdown-item\"> <i\r\n");
      out.write("								class=\"ti ti-user fs-6\"></i>\r\n");
      out.write("								<p class=\"mb-0 fs-3\">Thông tin cá nhân</p>\r\n");
      out.write("							</a> <a style=\"cursor: pointer;\"\r\n");
      out.write("								class=\"d-flex align-items-center gap-2 dropdown-item\"> <i\r\n");
      out.write("								class=\"ti ti-replace fs-6\"></i>\r\n");
      out.write("								<p class=\"mb-0 fs-3\">Đổi mật khẩu</p>\r\n");
      out.write("							</a> <a href=\"logoutadmin\"\r\n");
      out.write("								class=\"btn btn-outline-primary mx-3 mt-2 d-block\">Đăng xuất</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <button class=\"btn btn-primary float-end\" id=\"modal-add-notif\" role=\"button\">\r\n");
      out.write("                        <i class=\"ti ti-file-plus\"></i> Thông báo mới\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <h5 class=\"card-title fw-semibold mb-4 mt-2\">Danh Sách Thông báo</h5>\r\n");
      out.write("                    <div class=\"card\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <div class=\"table-responsive\">\r\n");
      out.write("                                <table class=\"table\">\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th scope=\"col\">#</th>\r\n");
      out.write("                                        <th scope=\"col\">User id</th>\r\n");
      out.write("                                        <th scope=\"col\">Họ tên</th>\r\n");
      out.write("                                        <th scope=\"col\">Kiểu thông báo</th>\r\n");
      out.write("                                        <th scope=\"col\">Nội dung</th>\r\n");
      out.write("                                        <th scope=\"col\">Video</th>\r\n");
      out.write("                                        <th scope=\"col\">Thời gian</th>\r\n");
      out.write("                                        <th scope=\"col\">Hành động</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("\r\n");
      out.write("									<tbody class=\"new-noti\"></tbody>\r\n");
      out.write("                                    <tbody class=\"render-new-noti\">\r\n");
      out.write("									\r\n");
      out.write("\r\n");
      out.write("                                    \r\n");
      out.write("\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal\" id=\"modal-create-noti\">\r\n");
      out.write("        <div class=\"modal-content\" style=\"\r\n");
      out.write("    max-width: 500px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    transform: translateY(-50%);\r\n");
      out.write("\">\r\n");
      out.write("            <div class=\"modal-header d-flex align-items-center\">\r\n");
      out.write("                <div class=\"modal-title text-center\" style=\"flex: 5;\">\r\n");
      out.write("                    Thêm thông báo\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"btn-close\" style=\"flex: 0.2;\" onclick=\"changeModal()\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"content-notification\">Nội dung</label>\r\n");
      out.write("                    <textarea type=\"text\" name=\"content-notification\" class=\"w-100 form-control\" style=\"height: 100px;\" autocomplete=\"off\" id=\"content-notification\" placeholder=\"Nhập nội dung thông báo\"></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"content-notification\">Kiểu thông báo</label>\r\n");
      out.write("                    <select name=\"select-type\" class=\"form-control\" id=\"select-type\">\r\n");
      out.write("                        <option value=\"0\">Tất cả</option>\r\n");
      out.write("                        <option value=\"1\">Đỗi tượng</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\" id=\"select-user-hidden\" style=\"display: none;\">\r\n");
      out.write("                    <label for=\"content-notification\">Đối tượng</label>\r\n");
      out.write("                    <select name=\"select-user\" class=\"form-control\" id=\"select-user\">\r\n");
      out.write("                        <option value=\"\">Chọn người dùng</option>\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("               \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer d-flex justify-content-end\">\r\n");
      out.write("                <div class=\"btn-default btn\" id=\"btn-close-modal\" onclick=\"changeModal()\">Hủy</div>\r\n");
      out.write("                <div class=\"btn btn-primary\" id=\"save-modal\">Lưu</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"modal\" id=\"modal-confirm\" >\r\n");
      out.write("    	<div class=\"modal-content\" style=\"\r\n");
      out.write("    max-width: 500px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    transform: translateY(-50%);\r\n");
      out.write("\">\r\n");
      out.write("    		<div class=\"modal-header\">\r\n");
      out.write("    			<div class=\"modal-title text-center\" style=\"flex:5; font-size:18px;\">\r\n");
      out.write("    				Xác nhận xóa thông báo. \r\n");
      out.write("    			\r\n");
      out.write("    			</div>\r\n");
      out.write("    			<div class=\"btn-close\" style=\"flex:0.2;\" onclick=\"changeConfirm(null)\"></div>\r\n");
      out.write("    		</div>\r\n");
      out.write("    		<div class=\"modal-body w-100 d-flex align-items-center justify-content-center\" >\r\n");
      out.write("    			<div class=\"content badge w-100 text-black text-center\" style=\"font-size:16px;\">\r\n");
      out.write("    				Bạn có chắc chắn muốn xóa thông báo này?\r\n");
      out.write("    			</div>\r\n");
      out.write("    		</div>\r\n");
      out.write("    		<div class=\"modal-footer d-flex justify-content-end\">\r\n");
      out.write("    			<div class=\"btn btn-default\" onclick=\"changeConfirm(null)\">Hủy</div>\r\n");
      out.write("    			<div class=\"btn btn-primary\" id=\"save-confirm-modal\" data-id=\"\">Ok</div>\r\n");
      out.write("    		</div>\r\n");
      out.write("    	</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"sweetalert2.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f10(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f11(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("\r\n");

Boolean loginAdmin = (Boolean) session.getAttribute("loginAdmin");
Boolean loginAdminFail = (Boolean) session.getAttribute("loginAdminFail");

if (loginAdmin != null) {
	if (loginAdmin) {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	showSwalAlert('success', 'Đăng nhập thành công !');\r\n");
      out.write("</script>\r\n");

} else {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	showSwalAlert('error', 'Sai thông tin đăng nhập !');\r\n");
      out.write("</script>\r\n");

}
session.removeAttribute("loginAdmin");
}

if (loginAdminFail != null) {
if (loginAdminFail) {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	showSwalAlert('warning', 'Tài khoản không hoạt động !');\r\n");
      out.write("</script>\r\n");

}
session.removeAttribute("loginAdminFail");
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var websocket = new WebSocket(\"ws://localhost:8080/BackEnd/notifications\");\r\n");
      out.write("websocket.onopen = function(message) {processOpen(message);};\r\n");
      out.write("websocket.onmessage = function(message) {processMessage(message);};\r\n");
      out.write("websocket.onclose = function(message) {processClose(message);};\r\n");
      out.write("websocket.onerror = function(message) {processError(message);};\r\n");
      out.write("\r\n");
      out.write("function processOpen(message){\r\n");
      out.write("	console.log('connect');\r\n");
      out.write("}\r\n");
      out.write("function processMessage(message){\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function processClose(message){\r\n");
      out.write("	console.log(\"dis\");\r\n");
      out.write("}\r\n");
      out.write("function processError(message){\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("	let page = 1;\r\n");
      out.write("	let noMoreNotification = false;\r\n");
      out.write("	getNotifications(true);\r\n");
      out.write("	\r\n");
      out.write("	var loop = 0;\r\n");
      out.write("	function getNotifications(newNoti = false){\r\n");
      out.write("		if(newNoti){\r\n");
      out.write("			page = 1;\r\n");
      out.write("			loop = 0;\r\n");
      out.write("			noMoreNotification = false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(!noMoreNotification){\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url:\"/BackEnd/getNotifications\",\r\n");
      out.write("				method:\"GET\",\r\n");
      out.write("				data:{\r\n");
      out.write("					page: page,\r\n");
      out.write("				},\r\n");
      out.write("				success:function(res){\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					if(page == 1){\r\n");
      out.write("						\r\n");
      out.write("						res.notifications.forEach(function(item){\r\n");
      out.write("							renderNotifications(item);\r\n");
      out.write("						})\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					else{\r\n");
      out.write("					\r\n");
      out.write("						res.notifications.forEach(function(item){\r\n");
      out.write("							renderNotifications(item);\r\n");
      out.write("						})\r\n");
      out.write("						\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					noMoreNotification = page >= res?.last_page;\r\n");
      out.write("					if(!noMoreNotification){\r\n");
      out.write("						page++;\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	actionOnScrollBottom(window, () => {\r\n");
      out.write("	    getNotifications();\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	function actionOnScrollBottom(element, callback) {\r\n");
      out.write("        $(element).on('scroll', () => {\r\n");
      out.write("            var scrollBottom = $(window).scrollTop() + $(window).height() === $(document).height();\r\n");
      out.write("            \r\n");
      out.write("            if (scrollBottom) {\r\n");
      out.write("                callback();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    $(\"#modal-add-notif\").click(function (){\r\n");
      out.write("        changeModal();\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("    $(\"#select-type\").change(function() {\r\n");
      out.write("        var data = $(this).val();\r\n");
      out.write("        \r\n");
      out.write("        if (data == 1) {\r\n");
      out.write("            $(\"#select-user-hidden\").css(\"display\", \"block\");\r\n");
      out.write("\r\n");
      out.write("        } else {\r\n");
      out.write("            $(\"#select-user-hidden\").css(\"display\", \"none\");\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function changeModal(){\r\n");
      out.write("        $(\"#modal-create-noti\").toggle();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    $('#save-modal').click(function (){\r\n");
      out.write("        var content = $('#content-notification').val();\r\n");
      out.write("        var type = $('#select-type').val();\r\n");
      out.write("        var user = $('#select-user').val();\r\n");
      out.write("        if(type == 1 && user == null){\r\n");
      out.write("        	return;\r\n");
      out.write("        }\r\n");
      out.write("        if(content != null && content.length > 0){\r\n");
      out.write("        	$('#content-notification').val(\"\");\r\n");
      out.write("        	$('#select-type').val(\"0\");\r\n");
      out.write("        	$('#select-user').val(\"\")\r\n");
      out.write("        	changeModal();\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: \"/BackEnd/createNotifications\",\r\n");
      out.write("                method: \"POST\",\r\n");
      out.write("                data:{\r\n");
      out.write("                    content: content,\r\n");
      out.write("                    type: type,\r\n");
      out.write("                    userid: user,\r\n");
      out.write("                },\r\n");
      out.write("                success:function (res){\r\n");
      out.write("                	const notifications = {\r\n");
      out.write("                		content: res.notification.content,\r\n");
      out.write("                		type: res.notification.type,\r\n");
      out.write("                		userId: res.notification.userId,\r\n");
      out.write("                		username: res.notification?.username \r\n");
      out.write("                	};\r\n");
      out.write("                	websocket.send(JSON.stringify(notifications));\r\n");
      out.write("                    renderNewNotification(res);\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("  	function renderNotifications(notification, i) {\r\n");
      out.write("	   loop++;\r\n");
      out.write("	    const notificationRow = $('<tr>')\r\n");
      out.write("	        .attr('data-notification-id', notification.id)\r\n");
      out.write("	        .addClass('notification-item');\r\n");
      out.write("	\r\n");
      out.write("	    $('<td>').text(loop).appendTo(notificationRow);\r\n");
      out.write("	\r\n");
      out.write("	    if (notification.userId !== 0) {\r\n");
      out.write("	        $('<td>').text(notification.userId).appendTo(notificationRow);\r\n");
      out.write("	        $('<td>').text(notification.username).appendTo(notificationRow);\r\n");
      out.write("	    } else {\r\n");
      out.write("	        $('<td>').html('<span class=\"badge bg-success-subtle text-success\">Null</span>').appendTo(notificationRow);\r\n");
      out.write("	        $('<td>').html('<span class=\"badge bg-success-subtle text-success\">Null</span>').appendTo(notificationRow);\r\n");
      out.write("	    }\r\n");
      out.write("	\r\n");
      out.write("	    if (notification.type === 0) {\r\n");
      out.write("	        $('<td>').html('<span class=\"badge bg-success-subtle text-success\">Tất cả</span>').appendTo(notificationRow);\r\n");
      out.write("	    } else {\r\n");
      out.write("	        $('<td>').html('<span class=\"badge bg-warning-subtle text-warning\">Người dùng</span>').appendTo(notificationRow);\r\n");
      out.write("	    }\r\n");
      out.write("	\r\n");
      out.write("	    $('<td>').text(notification.content).appendTo(notificationRow);\r\n");
      out.write("	    if(notification.href != null){\r\n");
      out.write("	    	$('<td>').text(notification.href).appendTo(notificationRow);\r\n");
      out.write("	    }else{\r\n");
      out.write("	    	$('<td>').html('<span class=\"badge bg-success-subtle text-success\">Null</span>').appendTo(notificationRow);\r\n");
      out.write("	    }\r\n");
      out.write("	   \r\n");
      out.write("	    $('<td>').text(notification.addDate).appendTo(notificationRow);\r\n");
      out.write("	\r\n");
      out.write("	    const actionTd = $('<td>');\r\n");
      out.write("	    const btnGroup = $('<div>').addClass('btn-group').attr('role', 'group');\r\n");
      out.write("	    const deleteButton = $('<button>')\r\n");
      out.write("	        .addClass('btn btn-danger ms-2 rounded-2')\r\n");
      out.write("	        .text('Xoá')\r\n");
      out.write("	        .attr('onclick', 'changeConfirm('+notification.id+')');\r\n");
      out.write("	\r\n");
      out.write("	    btnGroup.append(deleteButton);\r\n");
      out.write("	    actionTd.append(btnGroup);\r\n");
      out.write("	    notificationRow.append(actionTd);\r\n");
      out.write("	    $('.render-new-noti').append(notificationRow);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    function renderNewNotification(data) {\r\n");
      out.write("    	\r\n");
      out.write("    	var notification = data.notification;\r\n");
      out.write("    	var user = data.user;\r\n");
      out.write("                const notificationRow = $('<tr>')\r\n");
      out.write("                    .attr('data-notification-id', notification.id)\r\n");
      out.write("                    .addClass('notification-item');\r\n");
      out.write("\r\n");
      out.write("                $('<td>').text(notification.id).appendTo(notificationRow);\r\n");
      out.write("                \r\n");
      out.write("                if(user != null){\r\n");
      out.write("                	$('<td>').text(user.id).appendTo(notificationRow);\r\n");
      out.write("                	$('<td>').text(user.fullname).appendTo(notificationRow);\r\n");
      out.write("                }\r\n");
      out.write("                else{\r\n");
      out.write("                	$('<td>').html('<td><span class=\"badge bg-success-subtle text-success\">Null</span></td>').appendTo(notificationRow);\r\n");
      out.write("                	$('<td>').html('<td><span class=\"badge bg-success-subtle text-success\">Null</span></td>').appendTo(notificationRow);\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                if(notification.type == 0){\r\n");
      out.write("                	$('<td>').html('<td><span class=\"badge bg-success-subtle text-success\">All</span></td>').appendTo(notificationRow);\r\n");
      out.write("                }\r\n");
      out.write("                else{\r\n");
      out.write("                	$('<td>').html('<td><span class=\"badge bg-warning-subtle text-warning\">User</span></td>').appendTo(notificationRow);\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                $('<td>').text(notification.content).appendTo(notificationRow);\r\n");
      out.write("                if(notification.href != null){\r\n");
      out.write("        	    	$('<td>').text(notification.href).appendTo(notificationRow);\r\n");
      out.write("        	    }else{\r\n");
      out.write("        	    	$('<td>').html('<span class=\"badge bg-success-subtle text-success\">Null</span>').appendTo(notificationRow);\r\n");
      out.write("        	    }\r\n");
      out.write("                $('<td>').text(notification.addDate).appendTo(notificationRow);\r\n");
      out.write("\r\n");
      out.write("                const actionTd = $('<td>');\r\n");
      out.write("                const btnGroup = $('<div>').addClass('btn-group').attr('role', 'group');\r\n");
      out.write("                const deleteButton = $('<button>')\r\n");
      out.write("                    .addClass('btn btn-danger ms-2 rounded-2')\r\n");
      out.write("                    .text('Xoá')\r\n");
      out.write("                    .attr('onclick', 'changeConfirm('+notification.id+')');\r\n");
      out.write("\r\n");
      out.write("                btnGroup.append(deleteButton);\r\n");
      out.write("                actionTd.append(btnGroup);\r\n");
      out.write("                notificationRow.append(actionTd);\r\n");
      out.write("\r\n");
      out.write("                $('.new-noti').prepend(notificationRow);\r\n");
      out.write("     }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    $(\"#save-confirm-modal\").click(function(){\r\n");
      out.write("    	var data = $(this).attr(\"data-id\");\r\n");
      out.write("    	changeConfirm(data);\r\n");
      out.write("    	removeNotification(data);\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("    function removeNotification(id){\r\n");
      out.write("    	\r\n");
      out.write("    	const $notificationRow = $('tr[data-notification-id='+id+']');\r\n");
      out.write("        console.log(\"Found row:\", $notificationRow);\r\n");
      out.write("    	$.ajax({\r\n");
      out.write("    		url:\"/BackEnd/deleteNotifications\",\r\n");
      out.write("    		method: \"POST\",\r\n");
      out.write("    		data:{\r\n");
      out.write("    			id: id,\r\n");
      out.write("    		},\r\n");
      out.write("    		success:function(res){\r\n");
      out.write("    			\r\n");
      out.write("    			if(res.success){    				\r\n");
      out.write("    				$notificationRow.remove();\r\n");
      out.write("    			}\r\n");
      out.write("    			\r\n");
      out.write("    		}\r\n");
      out.write("    		\r\n");
      out.write("    	})\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    function changeConfirm(id){\r\n");
      out.write("    	\r\n");
      out.write("    	$('#modal-confirm').toggle();\r\n");
      out.write("    	\r\n");
      out.write("    	$(\"#save-confirm-modal\").attr(\"data-id\", id);\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /views/admin/common/head.jsp(1,24) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/views/admin/assets/images/favicon.png");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /views/admin/common/head.jsp(5,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/views/admin/assets/css/styles.min.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /views/admin/common/assied.jsp(10,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/views/admin/assets/images/logo.png");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /views/admin/common/header.jsp(23,11) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/views/admin/assets/images/user.jpg");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /views/admin/notifications.jsp(98,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /views/admin/notifications.jsp(98,24) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/views/admin/notifications.jsp(98,24) '${user}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${user}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                            <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.fullname}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write('-');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /views/admin/common/footer.jsp(6,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/views/template/user/js/jquery-3.3.1.min.js");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /views/admin/common/footer.jsp(7,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/views/admin/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /views/admin/common/footer.jsp(8,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/views/admin/assets/js/sidebarmenu.js");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /views/admin/common/footer.jsp(9,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/views/admin/assets/js/app.min.js");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /views/admin/common/footer.jsp(10,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/views/admin/assets/libs/apexcharts/dist/apexcharts.min.js");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /views/admin/common/footer.jsp(11,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("/views/admin/assets/libs/simplebar/dist/simplebar.js");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f10(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f10 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f10_reused = false;
    try {
      _jspx_th_c_005furl_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f10.setParent(null);
      // /views/admin/common/footer.jsp(12,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f10.setValue("/views/admin/assets/js/dashboard.js");
      int _jspx_eval_c_005furl_005f10 = _jspx_th_c_005furl_005f10.doStartTag();
      if (_jspx_th_c_005furl_005f10.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f10);
      _jspx_th_c_005furl_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f10, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f11(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f11 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f11_reused = false;
    try {
      _jspx_th_c_005furl_005f11.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f11.setParent(null);
      // /views/admin/common/footer.jsp(13,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f11.setValue("/views/admin/assets/js/validateAdmin.js");
      int _jspx_eval_c_005furl_005f11 = _jspx_th_c_005furl_005f11.doStartTag();
      if (_jspx_th_c_005furl_005f11.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f11);
      _jspx_th_c_005furl_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f11, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f11_reused);
    }
    return false;
  }
}
