/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.23
 * Generated at: 2024-05-21 15:08:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.common;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1602874032000L));
    _jspx_dependants.put("jar:file:/D:/BackEnd/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BackEnd/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602848772000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Footer Section Begin -->\r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("	<div class=\"page-up\">\r\n");
      out.write("		<a href=\"#\" id=\"scrollToTopButton\"><span class=\"arrow_carrot-up\"></span></a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-lg-3\">\r\n");
      out.write("				<div class=\"footer__logo\">\r\n");
      out.write("					<a href=\"index.jsp\"><img src=\"views/template/user/img/logo.png\"\r\n");
      out.write("						alt=\"\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-lg-6\">\r\n");
      out.write("				<div class=\"footer__nav\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li class=\"active\"><a href=\"index\">Trang Chủ</a></li>\r\n");
      out.write("						<li><a href=\"categories\">Danh Sách Phim</a></li>\r\n");
      out.write("						<li><a href=\"introduce\">Liên Hệ Với Tôi</a></li>\r\n");
      out.write("						<li><a href=\"profile\">Trang Cá Nhân</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-lg-3\">\r\n");
      out.write("				<p>\r\n");
      out.write("					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("					Copyright &copy;\r\n");
      out.write("					<script>\r\n");
      out.write("						document.write(new Date().getFullYear());\r\n");
      out.write("					</script>\r\n");
      out.write("					All rights reserved | Design and Developed <i class=\"fa fa-heart\"\r\n");
      out.write("						aria-hidden=\"true\"></i> by Quang Nhựt\r\n");
      out.write("					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("				</p>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- Footer Section End -->\r\n");
      out.write("\r\n");
      out.write("<!-- Search model Begin -->\r\n");
      out.write("<div class=\"search-model\">\r\n");
      out.write("	<div class=\"h-100 d-flex align-items-center justify-content-center\">\r\n");
      out.write("		<div class=\"search-close-switch\">\r\n");
      out.write("			<i class=\"icon_close\"></i>\r\n");
      out.write("		</div>\r\n");
      out.write("		<form action=\"search\" method=\"get\" class=\"search-model-form\"\r\n");
      out.write("			autocomplete=\"off\">\r\n");
      out.write("			<input type=\"text\" name=\"search\" id=\"search-input\"\r\n");
      out.write("				placeholder=\"Tìm kiếm.....\">\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"layout-messenger\" style=\"z-index:100;\">\r\n");
      out.write("	<div class=\"btn-icon-messenger position-fixed p-1\" style=\"bottom:0px; right:20px; z-index:100;\" onclick=\"openLayout()\">\r\n");
      out.write("		<div class=\"icon p-2  mb-2\" style=\"border-radius:50%;background-color:#ccc; \">\r\n");
      out.write("			<i class=\"fa-brands fa-facebook-messenger\" style=\"font-size:40px;\"></i>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"messenger-content position-fixed bg-white card messenger-layout messenger-messagingView scrollbutton-hidden\" style=\"width:330px; max-height:470px; right:20px; bottom:0; display:none;z-index:100;\">\r\n");
      out.write("		<div class=\"card-body p-0\">\r\n");
      out.write("		\r\n");
      out.write("			<div class=\"messenger-header d-flex align-items-center justify-content-between p-2\" style=\"border-bottom:1px solid #ccc;\">\r\n");
      out.write("				<div class=\"messenger-title text-bold\">\r\n");
      out.write("					Kênh thế giới\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"btn-close btn-hidden-layout\" onclick=\"hiddenLayout()\">\r\n");
      out.write("					<i class=\"fa-solid fa-minus\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"layout-main m-body messages-container app-scroll p-2\" style=\"opacity: 1; height: 508.8px; max-height: 369px; overflow: auto;\">\r\n");
      out.write("                <div class=\"messages\">\r\n");
      out.write("                \r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("              \r\n");
      out.write("			\r\n");
      out.write("			<div class=\"messenger-footer messenger-sendCard p-2\">\r\n");
      out.write("				<form id=\"message-form\" class=\"d-flex w-100 align-items-center\" method=\"POST\" action=\"\" enctype=\"multipart/form-data\">\r\n");
      out.write("			        <label class=\"handleFIle\">\r\n");
      out.write("			        	<span class=\"fas fa-plus-circle\"></span>\r\n");
      out.write("			        	<input disabled='disabled' type=\"file\" class=\"upload-attachment\" name=\"file\" accept=\"\" hidden/>\r\n");
      out.write("			        </label>\r\n");
      out.write("			        <button class=\"emoji-button\"></span><span class=\"fas fa-smile\"></button>\r\n");
      out.write("			        <textarea readonly='readonly' id=\"textMessage\" name=\"message\" class=\"m-send app-scroll w-100\" placeholder=\"Tin nhắn\" style=\"background-color: #ccc;\r\n");
      out.write("					    border-radius: 20px;\r\n");
      out.write("					    max-height: 146px;\r\n");
      out.write("					    overflow: hidden;\r\n");
      out.write("					    overflow-wrap: break-word;\r\n");
      out.write("					    height: 44px;\"></textarea>\r\n");
      out.write("			        <button disabled='disabled' class=\"send-button\">\r\n");
      out.write("			        	<span class=\"fas fa-paper-plane\"></span>\r\n");
      out.write("			        </button>\r\n");
      out.write("			    </form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"modal\" id=\"modal-confirm\" >\r\n");
      out.write("    	<div class=\"modal-content\" style=\"\r\n");
      out.write("		    max-width: 500px;\r\n");
      out.write("		    margin: 0 auto;\r\n");
      out.write("		    top: 50%;\r\n");
      out.write("		    transform: translateY(-50%);\r\n");
      out.write("		\">\r\n");
      out.write("    		<div class=\"modal-header\">\r\n");
      out.write("    			<div class=\"modal-title text-center\" style=\"flex:5; font-size:18px;\">\r\n");
      out.write("    				Xác nhận xóa tin nhắn. \r\n");
      out.write("    			\r\n");
      out.write("    			</div>\r\n");
      out.write("    			<div class=\"btn-close\" style=\"flex:0.2;\" onclick=\"changeConfirm(null)\"></div>\r\n");
      out.write("    		</div>\r\n");
      out.write("    		<div class=\"modal-body w-100 d-flex align-items-center justify-content-center\" >\r\n");
      out.write("    			<div class=\"content badge w-100 text-black text-center\" style=\"font-size:16px;\">\r\n");
      out.write("    				Bạn có chắc chắn muốn xóa tin nhắn này không?\r\n");
      out.write("    			</div>\r\n");
      out.write("    		</div>\r\n");
      out.write("    		<div class=\"modal-footer d-flex justify-content-end\">\r\n");
      out.write("    			<div class=\"btn btn-default\" onclick=\"changeConfirm(null)\">Hủy</div>\r\n");
      out.write("    			<div class=\"btn btn-primary\" id=\"save-confirm-modal\" data-id=\"\">Ok</div>\r\n");
      out.write("    		</div>\r\n");
      out.write("    	</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/@joeattardi/emoji-button@3.0.3/dist/index.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("\r\n");
      out.write("<!-- Js Plugins -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	const messengerTheme = 1;\r\n");
      out.write("	const messageInput = document.querySelector(\"#message-form .m-send\");\r\n");
      out.write("	const emojiButton = document.querySelector(\".emoji-button\");\r\n");
      out.write("	\r\n");
      out.write("	console.log(emojiButton);\r\n");
      out.write("	\r\n");
      out.write("	const emojiPicker = new EmojiButton({\r\n");
      out.write("	  theme: messengerTheme,\r\n");
      out.write("	  autoHide: false,\r\n");
      out.write("	  position: \"top-start\",\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	emojiButton.addEventListener(\"click\", (e) => {\r\n");
      out.write("	  e.preventDefault();\r\n");
      out.write("	  emojiPicker.togglePicker(emojiButton);\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	emojiPicker.on(\"emoji\", (emoji) => {\r\n");
      out.write("	  const el = messageInput;\r\n");
      out.write("	  const startPos = el.selectionStart;\r\n");
      out.write("	  const endPos = el.selectionEnd;\r\n");
      out.write("	  const value = el.value;\r\n");
      out.write("	\r\n");
      out.write("	  const newValue =\r\n");
      out.write("	    value.substring(0, startPos) +\r\n");
      out.write("	    emoji +\r\n");
      out.write("	    value.substring(endPos, value.length);\r\n");
      out.write("	\r\n");
      out.write("	  el.value = newValue;\r\n");
      out.write("	  el.selectionStart = el.selectionEnd = startPos + emoji.length;\r\n");
      out.write("	  el.focus();\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"sweetalert2.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	var websocket = new WebSocket(\"ws://localhost:8080/BackEnd/chat/1\");\r\n");
      out.write("	websocket.onopen = function(message) {processOpen(message);};\r\n");
      out.write("	websocket.onmessage = function(message) {processMessage(message);};\r\n");
      out.write("	websocket.onclose = function(message) {processClose(message);};\r\n");
      out.write("	websocket.onerror = function(message) {processError(message);};\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	console.log(websocket)\r\n");
      out.write("	function processOpen(message) {\r\n");
      out.write("		console.log(\"Server connect... \\n\")\r\n");
      out.write("	}\r\n");
      out.write("	function processMessage(message) {\r\n");
      out.write("		\r\n");
      out.write("		console.log(message);\r\n");
      out.write("		var check = JSON.parse(message.data);\r\n");
      out.write("		var action = check.action;\r\n");
      out.write("		if(action == \"send\"){\r\n");
      out.write("			\r\n");
      out.write("			var html = '';\r\n");
      out.write("			if(check.id == auth_id){\r\n");
      out.write("				html = appendMessengerUser(check);\r\n");
      out.write("			}\r\n");
      out.write("			else{\r\n");
      out.write("				html = appendMessengerOther(check);\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		    var appendHTML = document.querySelector('.messages');\r\n");
      out.write("		    \r\n");
      out.write("		   var scrolldiv = document.querySelector('.messages-container');\r\n");
      out.write("		   $('.messages').append(html);\r\n");
      out.write("		    if (appendHTML) {\r\n");
      out.write("		    	\r\n");
      out.write("		        scrolldiv.scrollTop = scrolldiv.scrollHeight;\r\n");
      out.write("		    } else {\r\n");
      out.write("		        console.error(\"Phần tử với class 'messages' không tồn tại.\");\r\n");
      out.write("		    }\r\n");
      out.write("			\r\n");
      out.write("		}else if(action == 'delete'){\r\n");
      out.write("			\r\n");
      out.write("			const name = $('.username[data-id='+ check.id +']');\r\n");
      out.write("			name.remove();\r\n");
      out.write("			const $notificationRow = $('.message-card[data-id='+ check.id +']');\r\n");
      out.write("			$notificationRow.remove();\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	function processClose(message) {\r\n");
      out.write("		console.log(\"Server Disconnect... \\n\");\r\n");
      out.write("	}\r\n");
      out.write("	function processError(message) {\r\n");
      out.write("		console.log(\"Error... \" + message +\" \\n\");\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function sendMessage() {\r\n");
      out.write("		var content = textMessage.value.trim();\r\n");
      out.write("		\r\n");
      out.write("	    if (typeof websocket !== 'undefined' && websocket.readyState === WebSocket.OPEN && (content.length > 0 || $('.img-preview').attr('src') != null)) {\r\n");
      out.write("	    		if($('.img-preview').attr('src') == null){\r\n");
      out.write("	    			var message = {\r\n");
      out.write("	   		    	     action: 'send',\r\n");
      out.write("	   		    	     messages: textMessage.value,\r\n");
      out.write("	   		    	     file:\"\",\r\n");
      out.write("	   		    	};\r\n");
      out.write("	   	    	\r\n");
      out.write("	   		        websocket.send(JSON.stringify(message));\r\n");
      out.write("	   		        textMessage.value = \"\";\r\n");
      out.write("	   		        cancelAttachment();\r\n");
      out.write("	    		}\r\n");
      out.write("	    		else{\r\n");
      out.write("	    			sendfile($('.img-preview').attr('src'),textMessage.value);\r\n");
      out.write("	    		}\r\n");
      out.write("	    } \r\n");
      out.write("	    textMessage.value = \"\";\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("    $(\"#message-form\").on(\"submit\", (e) => {\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        sendMessage();\r\n");
      out.write("        $('.messages-container').css({height: 369 + \"px\"});\r\n");
      out.write("        $('.handleFIle').removeClass('d-none');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    $(\"#message-form .m-send\").on(\"keyup\", (e) => {\r\n");
      out.write("        \r\n");
      out.write("        if (e.which == 13 || e.keyCode == 13) {\r\n");
      out.write("           \r\n");
      out.write("            if (!e.shiftKey) {\r\n");
      out.write("            	\r\n");
      out.write("            	\r\n");
      out.write("                sendMessage();\r\n");
      out.write("                $('.messages-container').css({height: 369 + \"px\"});\r\n");
      out.write("                $('.handleFIle').removeClass('d-none');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("	\r\n");
      out.write("    \r\n");
      out.write("    function sendfile(file, content){\r\n");
      out.write("    	$.ajax({\r\n");
      out.write("    		url:\"/BackEnd/sendfile\",\r\n");
      out.write("    		method:\"POST\",\r\n");
      out.write("    		data:{\r\n");
      out.write("    			file: file,\r\n");
      out.write("    		},\r\n");
      out.write("    		success:function(res){\r\n");
      out.write("    			console.log(res);\r\n");
      out.write("    			var message = {\r\n");
      out.write("	   		    	     action: 'send',\r\n");
      out.write("	   		    	     messages: content ,\r\n");
      out.write("	   		    	     file: res.,\r\n");
      out.write("	   		    	};\r\n");
      out.write("	   	    	\r\n");
      out.write("	   		        websocket.send(JSON.stringify(message));\r\n");
      out.write("	   		        textMessage.value = \"\";\r\n");
      out.write("	   		        cancelAttachment();\r\n");
      out.write("    		}\r\n");
      out.write("    	})\r\n");
      out.write("    }\r\n");
      out.write("	\r\n");
      out.write("	$(document).on('click', '.delete-btn', function() {\r\n");
      out.write("	    var messageId = $(this).data('id');\r\n");
      out.write("	    \r\n");
      out.write("	    changeConfirm(messageId);\r\n");
      out.write("	    \r\n");
      out.write("	});\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    $(\"#save-confirm-modal\").click(function(){\r\n");
      out.write("    	var data = $(this).attr(\"data-id\");\r\n");
      out.write("    	\r\n");
      out.write("    	console.log(data);\r\n");
      out.write("    	changeConfirm(data);\r\n");
      out.write("    	 var message = {\r\n");
      out.write("    		 action: 'delete',\r\n");
      out.write("    		 id: data\r\n");
      out.write("    	};\r\n");
      out.write("    	websocket.send(JSON.stringify(message));\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    function changeConfirm(id){\r\n");
      out.write("    	\r\n");
      out.write("    	$('#modal-confirm').toggle();\r\n");
      out.write("    	\r\n");
      out.write("    	$(\"#save-confirm-modal\").attr(\"data-id\", id);\r\n");
      out.write("    	\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    var data = localStorage.getItem(\"message\") ?? null;\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    if(data == null){\r\n");
      out.write("    	localStorage.setItem(\"message\", 0);\r\n");
      out.write("    	\r\n");
      out.write("    }else{\r\n");
      out.write("    	if(data == 1){\r\n");
      out.write("    		openLayout();\r\n");
      out.write("    		message_img();\r\n");
      out.write("    	}\r\n");
      out.write("    	\r\n");
      out.write("    }\r\n");
      out.write("    const allowedExtensions = ['jpg', 'jpeg', 'png', 'gif'];\r\n");
      out.write("    const maxUploadSize = 5 * 1024 * 1024; // 5MB\r\n");
      out.write("    \r\n");
      out.write("    function message_img(){\r\n");
      out.write("    	  $(\"body\").on(\"change\", \".upload-attachment\", (e) => {\r\n");
      out.write("    	    let file = e.target.files[0];\r\n");
      out.write("    	    if (!attachmentValidates(file)) return false;\r\n");
      out.write("    	    let reader = new FileReader();\r\n");
      out.write("    	    let sendCard = $(\".messenger-sendCard\");\r\n");
      out.write("    	    reader.readAsDataURL(file);\r\n");
      out.write("    	    reader.addEventListener(\"loadstart\", (e) => {\r\n");
      out.write("    	        $(\"#message-form\").before(loadingSVG());\r\n");
      out.write("    	    });\r\n");
      out.write("    	    reader.addEventListener(\"load\", (e) => {\r\n");
      out.write("    	        $(\".messenger-sendCard\").find(\".loadingSVG\").remove();\r\n");
      out.write("    	        if (!file.type.match(\"image.*\")) {\r\n");
      out.write("    	           \r\n");
      out.write("    	            sendCard.find(\".attachment-preview\").remove(); // older one\r\n");
      out.write("    	            sendCard.prepend(attachmentTemplate(\"file\", file.name));\r\n");
      out.write("    	        } else {\r\n");
      out.write("    	            \r\n");
      out.write("    	            sendCard.find(\".attachment-preview\").remove(); // older one\r\n");
      out.write("    	            sendCard.prepend(\r\n");
      out.write("    	                attachmentTemplate(\"image\", file.name, e.target.result)\r\n");
      out.write("    	            );\r\n");
      out.write("    	          \r\n");
      out.write("    	            const h = $('.messenger-messagingView').height() || 0; \r\n");
      out.write("    	            \r\n");
      out.write("    	         // Tạo một đối tượng ảnh mới\r\n");
      out.write("    	            const img = new Image();\r\n");
      out.write("					let b = 0; \r\n");
      out.write("					\r\n");
      out.write("					// Gán src của ảnh mới bằng src của ảnh có class 'img-preview'\r\n");
      out.write("					img.src = $('.img-preview').attr('src');\r\n");
      out.write("					\r\n");
      out.write("					// Khi ảnh tải xong, hàm này sẽ được gọi\r\n");
      out.write("					img.onload = function() {\r\n");
      out.write("					  \r\n");
      out.write("					  const w = img.width / 260;\r\n");
      out.write("					  b = img.height / w;\r\n");
      out.write("					  const m = 368 -  b - 25;\r\n");
      out.write("					  \r\n");
      out.write("					 \r\n");
      out.write("					  if (h > 0) {\r\n");
      out.write("	    	                $(\".messenger-messagingView\").css({ height: h + \"px\" });\r\n");
      out.write("	    	                $('.messages-container').css({ height: m + \"px\" });\r\n");
      out.write("	    	            }\r\n");
      out.write("					};\r\n");
      out.write("    	            \r\n");
      out.write("    	            \r\n");
      out.write("    	          \r\n");
      out.write("    	            \r\n");
      out.write("    	        }\r\n");
      out.write("    	    });\r\n");
      out.write("    	    \r\n");
      out.write("    	    });\r\n");
      out.write("    	}\r\n");
      out.write("\r\n");
      out.write("		    function attachmentValidates(file) {\r\n");
      out.write("		        const fileElement = $(\".upload-attachment\");\r\n");
      out.write("		        const { name: fileName, size: fileSize } = file;\r\n");
      out.write("		        const fileExtension = fileName.split(\".\").pop().toLowerCase();\r\n");
      out.write("		\r\n");
      out.write("		        if (!allowedExtensions.includes(fileExtension)) {\r\n");
      out.write("		            alert(\"File type not allowed\");\r\n");
      out.write("		            fileElement.val(\"\");\r\n");
      out.write("		            return false;\r\n");
      out.write("		        }\r\n");
      out.write("		\r\n");
      out.write("		        // Validate file size.\r\n");
      out.write("		        if (fileSize > maxUploadSize) {\r\n");
      out.write("		            alert(\"File is too large!\");\r\n");
      out.write("		            fileElement.val(\"\");\r\n");
      out.write("		            return false;\r\n");
      out.write("		        }\r\n");
      out.write("		        return true;\r\n");
      out.write("		    }\r\n");
      out.write("		    function loadingSVG(size = \"25px\", className = \"\", style = \"\") {\r\n");
      out.write("		    	 return `\r\n");
      out.write("		    	<svg style=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${style}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"loadingSVG ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${className}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" xmlns=\"http://www.w3.org/2000/svg\" width=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${size}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" height=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${size}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" viewBox=\"0 0 40 40\" stroke=\"var(--primary-color)fff\">\r\n");
      out.write("		    	<g fill=\"none\" fill-rule=\"evenodd\">\r\n");
      out.write("		    	<g transform=\"translate(2 2)\" stroke-width=\"3\">\r\n");
      out.write("		    	<circle stroke-opacity=\".1\" cx=\"18\" cy=\"18\" r=\"18\"></circle>\r\n");
      out.write("		    	<path d=\"M36 18c0-9.94-8.06-18-18-18\" transform=\"rotate(349.311 18 18)\">\r\n");
      out.write("		    	<animateTransform attributeName=\"transform\" type=\"rotate\" from=\"0 18 18\" to=\"360 18 18\" dur=\".8s\" repeatCount=\"indefinite\"></animateTransform>\r\n");
      out.write("		    	</path>\r\n");
      out.write("		    	</g>\r\n");
      out.write("		    	</g>\r\n");
      out.write("		    	</svg>\r\n");
      out.write("		    	`;\r\n");
      out.write("		    }\r\n");
      out.write("		    \r\n");
      out.write("		    function attachmentTemplate(fileType, fileName, imgURL = null) {\r\n");
      out.write("		    	 if (fileType != \"image\") {\r\n");
      out.write("		    	   return (\r\n");
      out.write("		    	     `\r\n");
      out.write("		    	     <div class=\"attachment-preview\">\r\n");
      out.write("		    	         <span class=\"fas fa-times cancel\"></span>\r\n");
      out.write("		    	         <p style=\"padding:0px 30px;\"><span class=\"fas fa-file\">\r\n");
      out.write("		    	     </div>\r\n");
      out.write("		    	     `\r\n");
      out.write("		    	   );\r\n");
      out.write("		    	 } else {\r\n");
      out.write("		    	   const imageSrc = imgURL; \r\n");
      out.write("		    	  \r\n");
      out.write("		    	   return (\r\n");
      out.write("		    	     '<div class=\"attachment-preview position-relative p-1\"><span class=\"fas fa-times cancel text-white\"></span><div class=\"image-file chat-image\" ><img loading=\"lazy\" class=\"img-preview\" style=\"width: 100%;\" src=\"'+imageSrc+'\" /></div><p>'\r\n");
      out.write("		    	   );\r\n");
      out.write("		    	 }\r\n");
      out.write("		    	}\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("<!-- đăng nhập thành công -->\r\n");



Boolean loginSuccess = (Boolean) session.getAttribute("loginSuccess");
Boolean loginFail = (Boolean) session.getAttribute("loginFail");
if (loginSuccess != null) {
	if (loginSuccess) {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	showSwalAlert('success', 'Đăng nhập thành công!');\r\n");
      out.write("</script>\r\n");

} else {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	showSwalAlert('error', 'Sai thông tin người dùng !');\r\n");
      out.write("</script>\r\n");

}
session.removeAttribute("loginSuccess");
}

if (loginFail != null) {
if (loginFail) {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	showSwalAlert('warning', 'Tài khoản không hoạt động !');\r\n");
      out.write("</script>\r\n");

}
session.removeAttribute("loginFail");
}

      out.write("\r\n");
      out.write("\r\n");

Boolean registerSuccess = (Boolean) session.getAttribute("registerSuccess");
if (registerSuccess != null) {
	if (registerSuccess) {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	showCenterAlert('success', 'Thành công !',\r\n");
      out.write("			'Một email xác minh đã gửi đến địa chỉ email của bạn !');\r\n");
      out.write("</script>\r\n");

}
session.removeAttribute("registerSuccess");
}

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /views/common/footer.jsp(187,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/views/template/user/js/jquery-3.3.1.min.js");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /views/common/footer.jsp(188,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/views/template/user/js/bootstrap.min.js");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /views/common/footer.jsp(189,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/views/template/user/js/player.js");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /views/common/footer.jsp(190,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/views/template/user/js/jquery.nice-select.min.js");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /views/common/footer.jsp(191,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/views/template/user/js/mixitup.min.js");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /views/common/footer.jsp(192,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/views/template/user/js/jquery.slicknav.js");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /views/common/footer.jsp(193,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/views/template/user/js/owl.carousel.min.js");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /views/common/footer.jsp(194,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/views/template/user/js/main.js");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /views/common/footer.jsp(195,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/views/template/user/js/validateUser.js");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /views/common/footer.jsp(199,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("/views/template/user/js/chat.js");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }
}
