/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.23
 * Generated at: 2024-05-21 17:23:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.common;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class head_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<link rel=\"icon\" href=\"<c:url value='/views/template/user/img/favicon.png'/>\" type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("<!-- Google Font -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("<meta name=\"auth_id\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.currentUser.id }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write(" \r\n");
      out.write("<!-- Css Styles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"sweetalert2.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"<c:url value='/views/template/user/css/bootstrap.min.css'/>\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"<c:url value='/views/template/user/css/font-awesome.min.css'/>\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"<c:url value='/views/template/user/css/elegant-icons.css'/>\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"<c:url value='/views/template/user/css/plyr.css'/>\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"<c:url value='/views/template/user/css/nice-select.css'/>\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"<c:url value='/views/template/user/css/owl.carousel.min.css'/>\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"<c:url value='/views/template/user/css/slicknav.min.css'/>\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"<c:url value='/views/template/user/css/style.css'/>\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"<c:url value='/views/template/user/css/messenger.css'/>\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".m-send{\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    resize: none;\r\n");
      out.write("    \r\n");
      out.write("    font-family: sans-serif;\r\n");
      out.write("    height: 44px;\r\n");
      out.write("    max-height: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".handleFIle{\r\n");
      out.write("	border:none;\r\n");
      out.write("	padding:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".messenger-sendCard button, .messenger-sendCard button:active, .messenger-sendCard button:focus{\r\n");
      out.write("	    border: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    background: none;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#message-form label{\r\n");
      out.write("	margin:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper{\r\n");
      out.write("	z-index:100;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".messenger-sendCard span{\r\n");
      out.write("	    margin: 9px 10px;\r\n");
      out.write("    color: #bdcbd6;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    font-size: 21px;\r\n");
      out.write("    transition: transform 0.15s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".message-card.mc-sender .message-card-content{\r\n");
      out.write("		align-items: end;\r\n");
      out.write("    border-radius: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".message-card .message-card-content{\r\n");
      out.write("	display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    gap: 4px;\r\n");
      out.write("    max-width: 75%;\r\n");
      out.write("    border-radius: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".message-card div{\r\n");
      out.write("	    margin-top: 0p\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".message-card .message{\r\n");
      out.write("	margin: 0;\r\n");
      out.write("    padding: 6px 15px;\r\n");
      out.write("    padding-bottom: 5px;\r\n");
      out.write("    width: fit-content;\r\n");
      out.write("    width: -webkit-fit-content;\r\n");
      out.write("    border-radius: 20px;\r\n");
      out.write("    word-break: break-word;\r\n");
      out.write("    display: table-cell;\r\n");
      out.write("    background-color: #ccc;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".message-card.mc-sender .message-card-content .message{\r\n");
      out.write("	background-color: #0084ff !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".message-card.mc-sender .message{\r\n");
      out.write("	direction: ltr;\r\n");
      out.write("    background: #ccc !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".message-card{\r\n");
      out.write("	display: flex;\r\n");
      out.write("    flex-direction: row;\r\n");
      out.write("    gap: 0.5rem;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    width: 100% !important;\r\n");
      out.write("    margin: 2px 5px;\r\n");
      out.write("    width: calc(100% - 30px);\r\n");
      out.write("    justify-content: flex-start;\r\n");
      out.write("    font-family: Arial, Helvetica, sans-serif !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".message-card.mc-sender{\r\n");
      out.write("	justify-content: flex-end;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".message-card:hover .actions .delete-btn{\r\n");
      out.write("	display:block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".message-card .actions .delete-btn{\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	display:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (min-width: 450px) and (max-width: 600px) {\r\n");
      out.write("   \r\n");
      out.write("    .messenger-content{\r\n");
      out.write("    	max-width:100% !important;\r\n");
      out.write("    	width:100% !important;\r\n");
      out.write("    	right:0 !important;\r\n");
      out.write("    	height:100% !important;\r\n");
      out.write("    	max-height:100% !important;\r\n");
      out.write("    }\r\n");
      out.write("    .layout-main{\r\n");
      out.write("    	max-height:100% !important;\r\n");
      out.write("    	\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".message-card .image-file, .attachment-preview .image-file{\r\n");
      out.write("\r\n");
      out.write("cursor: pointer;\r\n");
      out.write("    width: 140px;\r\n");
      out.write("    height: 70px;\r\n");
      out.write("    border-radius: 6px;\r\n");
      out.write("    width: 260px;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    background-color: #f7f7f7;\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    background-position: center center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".attachment-preview > .cancel:first-child{\r\n");
      out.write("	position: absolute;\r\n");
      out.write("    background: rgba(0, 0, 0, 0.33);\r\n");
      out.write("    width: 20px;\r\n");
      out.write("    height: 20px;\r\n");
      out.write("    padding: 3px;\r\n");
      out.write("    border-radius: 100%;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    top: 10px;\r\n");
      out.write("    color: var(--primary-color);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".imageModal {\r\n");
      out.write("    display: none;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    z-index: 50;\r\n");
      out.write("    padding-top: 100px;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    overflow: auto;\r\n");
      out.write("    background-color: rgb(0, 0, 0);\r\n");
      out.write("    background-color: rgba(0, 0, 0, 0.9);\r\n");
      out.write("    z-index: 200000001;\r\n");
      out.write("  }\r\n");
      out.write("  .imageModal-content {\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    display: block;\r\n");
      out.write("    height: calc(100vh - 150px);\r\n");
      out.write("  }\r\n");
      out.write("  .imageModal-content {\r\n");
      out.write("    -webkit-animation-name: zoom;\r\n");
      out.write("    -webkit-animation-duration: 0.15s;\r\n");
      out.write("    animation-name: zoom;\r\n");
      out.write("    animation-duration: 0.15s;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  @-webkit-keyframes zoom {\r\n");
      out.write("    from {\r\n");
      out.write("      -webkit-transform: scale(0);\r\n");
      out.write("    }\r\n");
      out.write("    to {\r\n");
      out.write("      -webkit-transform: scale(1);\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("  @keyframes zoom {\r\n");
      out.write("    from {\r\n");
      out.write("      transform: scale(0);\r\n");
      out.write("    }\r\n");
      out.write("    to {\r\n");
      out.write("      transform: scale(1);\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .imageModal-close {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 15px;\r\n");
      out.write("    right: 35px;\r\n");
      out.write("    color: #f1f1f1 !important;\r\n");
      out.write("    font-size: 40px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    transition: 0.3s;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .imageModal-close:hover,\r\n");
      out.write("  .imageModal-close:focus {\r\n");
      out.write("    color: #bbb;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
